language: node_js
node_js:
  - '8'

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - EMBER_TRY_SCENARIO=ember-lts-2.12
    - EMBER_TRY_SCENARIO=ember-lts-2.16
    - EMBER_TRY_SCENARIO=ember-lts-2.18
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn lint:js
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try $EMBER_TRY_SCENARIO --skip-cleanup

after_success:
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

deploy:
  provider: heroku
  api_key:
    secure: WjnO05P979UjfM/HZhuCqLho4x1axmz11uL2AJPyJiCx05LHEty7Nd4E9CZROAQSVJTQsDRmjEqqAYTKk4O6NhPPRE8joyW/GKplUMYpguo4YPxKE1UfPYof4+CPWmXaG82nOvgeasUPu5dKXQqpIduBAVjQrudFXPezBtqLrrWc/pfmemqjcyjHGZRsmPVsFo8pW8P6Psbd8/v8jmsLFM9etC5jUmRnYnar4P13M2cWy3LPl4Yd8mDtqCdBqpqsDAG53symLk6eXKNd5ANkePgOq3WvaUgTYxnqQNrmDNKHdt1pCUVruKPBKS6wudcLzLufoxZBVOfjXck4XB42WJieE9mHUECkJOp/JuGnCsiJUW3AeN8mx7i8+YJAQSEvIKxvo9o431ANKBhkFKkxw2PahxKPKq1+su21QR2P2+nbbKmjJxHG663nULr0rEzdNCNQmSqwmRxUAmFgL2P/WIkFxGGVtGehC31lMEwXuNQAG/JKdPJOYstdsk7SWfRVz+SeMqH+C+DxikkHy9BhZHnyIxJag4WlNvHEWTUNLirGLE09kQpObrb+Mw0pOMdzXox6jX3ltZlnTUjVXuHikg2wPt4VWj1cC0SZOqHDgpiylu0pgsNDV+oJLEXtRT/L5t0ua82VWfhSknjScJ1Ior4nXD/uetVcsP4dLGyo45Q=
  app: ember-oembed-demo
  on:
    repo: mike-north/ember-oembed
