language: node_js
node_js:
- '6'
sudo: false
cache:
  yarn: true
env:
- EMBER_TRY_SCENARIO=ember-lts-2.4
- EMBER_TRY_SCENARIO=ember-lts-2.8
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
- EMBER_TRY_SCENARIO=ember-default
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add greenkeeper-lockfile@1
- yarn global add phantomjs-prebuilt
- phantomjs --version

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

install:
- yarn install --no-lockfile
script:
- node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
deploy:
  provider: heroku
  api_key:
    secure: WjnO05P979UjfM/HZhuCqLho4x1axmz11uL2AJPyJiCx05LHEty7Nd4E9CZROAQSVJTQsDRmjEqqAYTKk4O6NhPPRE8joyW/GKplUMYpguo4YPxKE1UfPYof4+CPWmXaG82nOvgeasUPu5dKXQqpIduBAVjQrudFXPezBtqLrrWc/pfmemqjcyjHGZRsmPVsFo8pW8P6Psbd8/v8jmsLFM9etC5jUmRnYnar4P13M2cWy3LPl4Yd8mDtqCdBqpqsDAG53symLk6eXKNd5ANkePgOq3WvaUgTYxnqQNrmDNKHdt1pCUVruKPBKS6wudcLzLufoxZBVOfjXck4XB42WJieE9mHUECkJOp/JuGnCsiJUW3AeN8mx7i8+YJAQSEvIKxvo9o431ANKBhkFKkxw2PahxKPKq1+su21QR2P2+nbbKmjJxHG663nULr0rEzdNCNQmSqwmRxUAmFgL2P/WIkFxGGVtGehC31lMEwXuNQAG/JKdPJOYstdsk7SWfRVz+SeMqH+C+DxikkHy9BhZHnyIxJag4WlNvHEWTUNLirGLE09kQpObrb+Mw0pOMdzXox6jX3ltZlnTUjVXuHikg2wPt4VWj1cC0SZOqHDgpiylu0pgsNDV+oJLEXtRT/L5t0ua82VWfhSknjScJ1Ior4nXD/uetVcsP4dLGyo45Q=
  app: ember-oembed-demo
  on:
    repo: mike-north/ember-oembed
