language: node_js
node_js:
  - '8'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  yarn: true
env:
  global:
    - JOBS=1

stages:
  - 'Tests'
  - 'Additional Tests'
  - 'Canary Tests'
  - name: 'Deploy'
    if: branch = master AND type = push

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
  include:
    - stage: 'Tests'
      name: 'Tests'
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:js
        - ember test

    - name: 'Floating Dependencies'
      script:
        - ember test

    - stage: 'Additional Tests'
      node_js: 10
      env: EMBER_TRY_SCENARIO=ember-lts-2.12
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: heroku
  api_key:
    secure: JvB+Ct0sdg6e5ERIu34E/5WFFBAgCpqgW7pxY3z+nCXWEtCKUwWyt+Y66yU5wjSDHlDLVYnudTmGNQMUvyKiZ/OQ0bJ7FU6OoIrcfoKGqA9+REDqkPUEiQQ0/eYNwoM+JQ2qxP4RXbb8u/ghG4S4IYbIEEMAVK75VKiHj7Kp5fVRtdwK2PkcheFz3opvCIb5K1mARLbz00sRIXEO/UjHtlgJFMHTtXSAYXJhPyKbE6JMrzc6UrGjukGaFHgbNjI3p39WIUceWE+Af1lWCbLQQ79qHYJHnr0pVuLuqXXSMO/SukaOwArAnFb4RVtw6n/7+ivwEj/2wLbMLs+c1ItEymws96Os5D8o9LfH0RrvO0OZBT/OD0jC+AXGbszsfZ0K9ONFQtfUILIe2dRxBikBGQyAlfs4XUImHKPksDo6lAqgrHWYyIaZS7EnWgjW2vodMHKqr9UVbGEDv03R43QWS+WUkODroW6dk3e7kxWmzy+3Fehimy6YQhlY48M6oGGQxgq4tr4FF2ersJpe4Hwv2MJdC10NNm1YPNpzAxw6PStSaLjB0NjgPLC+PfzkIYZTxOJRzp+cnI83l0SD4CZzLh/F7wyV/8Er0y4vSXbsFbwTvK1Jtvvs0e4k2d6R2AkVlVGOawshYqgMdOYTUVhRLMVWkrGnrB9wSf0P9qlDWB0=
  app: ember-oembed-demo
  on:
    repo: mike-north/ember-oembed
